language: rust
rust: nightly
dist: xenial

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=clang++; fi

script:
  - cargo test --release --verbose
  - cargo test --release --verbose --features egl  # Doesn’t do anything, but should still build
