language: rust
rust: nightly

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8; fi

script:
  - cargo test --verbose

notifications:
  webhooks: http://build.servo.org:54856/travis
