[package]
name = "mozangle"
version = "0.1.0"
authors = ["The ANGLE Project Authors"]
license = " BSD-3-Clause"

[lib]
path = "lib.rs"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }

[features]
egl = []  # Only supported on Windows
