[package]
name = "mozangle"
version = "0.1.0"
authors = ["The ANGLE Project Authors", "The Servo Project Developers"]
license = " BSD-3-Clause"

[dependencies]
lazy_static = "1.0"

[build-dependencies]
cc = { version = "1.0.5", features = ["parallel"] }
gl_generator = {version = "0.9.0", optional = true}

[features]
egl = ["gl_generator"]  # Only supported on Windows
